services:
  accounts:
    image: donny10/accounts:s4
    ports:
     - "8080:8080"
    container_name: accounts-ms
    deploy:
      resources:
        limits:
          memory: "700m"
    networks:
      - bank-network
  loans:
    image: donny10/loans:s4
    ports:
        - "8090:8090"
    container_name: loans-ms
    deploy:
      resources:
        limits:
          memory: "700m"
    networks:
      - bank-network
  cards:
    image: donny10/cards:s4
    ports:
      - "9000:9000"
    container_name: cards-ms
    deploy:
      resources:
        limits:
          memory: "700m"
    networks:
      - bank-network

networks:
  bank-network:
    driver: bridge